# Generated by Django 5.2.6 on 2025-11-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestrequest',
            name='reset_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
