# Generated by Django 5.2.6 on 2025-11-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_guestrequest_reset_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestrequest',
            name='reset_code',
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
