# Generated by Django 5.2.6 on 2025-11-19 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_guestrequest_reset_code_customuser_reset_code'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='accounts_keys',
        ),
    ]
